workflows:
  ios-workflow:
    name: "iOS Workflow"
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      vars:
        XCODE_WORKSPACE: "App.xcworkspace"
        XCODE_SCHEME: "App"
      xcode: latest
      node: latest
    scripts:
      - name: Install npm dependencies
        script: npm install
      - name: Install CocoaPods dependencies
        script: |
          cd ios/App
          pod install
      - name: Build web assets
        script: npm run build
      - name: Sync Capacitor
        script: npx cap sync
      - name: Set up code signing
        script: xcode-project use-profiles
      - name: Build IPA for distribution
        script: |
          cd ios/App
          xcode-project build-ipa \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME"
    artifacts:
      - ios/App/build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    publishing:
      email:
        recipients:
          - poornachandrach99899@gmail.com
        notify:
          success: true
          failure: true
